### ISSUE TITLE
Remove Token during registration process?

### ISSUE THREAD

**Issue by tadhgboyle** [RedstonerServer/redstoner.com#14]
Hey guys, sorry for all these issues, don't have any other way of contacting you hehe.
http://138.68.227.34/home
I am wondering if there is a way I could remove the need for a token during the registration process? I have no server, I am just messing around on the site, I dont want to goto the hassle of setting up a server as well... 
Thanks again.

**Comment by Minenash** [comment]
I'm ignoring the question for now, as I'm not at my pc, but you can contact us through our subreddit, https://www.reddit.com/r/Redstoner Which for the most part is barren due to us having a forum.

**Comment by ThatSimplex** [comment]
If you go into [this file](https://github.com/RedstonerServer/redstoner.com/blob/master/db/seeds.rb) you can create new users and just set confirmed to true. That way you have created a new user without the use of tokens. I also think you can remove the token entirely by changing the code in [here](https://github.com/RedstonerServer/redstoner.com/blob/master/app/controllers/users_controller.rb#L87). I hope this helps you.

**Comment by tadhgboyle** [comment]
Hey Fusty, not sure I understand what you mean, I have tried to set the value to 'false' on new.html.erb and that doesnt work, How could I add a user to the first file you  linked? What code would I remove in the second file?
Thanks :100:

**Comment by ThatSimplex** [comment]
In the first file you can just copy the thing for the deleted_user but change name, uuid and other information to fit the new user. I am not completely sure what you need to remove in the second file, but if you look [here](https://github.com/RedstonerServer/redstoner.com/blob/master/app/controllers/users_controller.rb#L98) it checks if the token is valid, so I assume you need to remove that or something with that. Also next time you say a name of a file, please send a link with it, because there are multiple files with the name new.html.erb, but I assume you mean [this one](https://github.com/RedstonerServer/redstoner.com/blob/master/app/views/users/new.html.erb)

**Comment by tadhgboyle** [comment]
Yep I mean that file :D 
The user_controller.rb file tooks like it is mainly about token validation, hopefully jomo can come to the rescue. 
Cheers.

**Comment by ThatSimplex** [comment]
But if you remove the token validation check, you will not have a problem with the token will you?

**Comment by tadhgboyle** [comment]
Alright, Ill back it up and give it a shot.

**Comment by ThatSimplex** [comment]
Can I ask how did it go? Did you find a solution or are you still wondering how you should do it?

**Comment by tadhgboyle** [comment]
Hey.
I tried removing everything to do with a token and it kept crashing and
503ing. Sort of given up haha. Thanks.
